plan/milestones.md

Add a new `plan/milestone.md` file, according to our shared [word file](https://microsoft.sharepoint.com/:w:/t/AMLDataScience-FederatedLearning/EXCpr8jLeZ1Ns40YmY1kAUABTfD4vV8_LDy8po6yHRn2Ew).
Priority: _low_.

Add ./plan/milestones.md

---

automated_provisioning/sample_job/job.yml

tiny PR to update docker image version in sample test job to avoid docker vulnerability issue

update docker image version in sample test job to avoid docker vulnerability issue

---

automated_provisioning/ps/ConnectSiloToOrchestrator.ps1

Just remove 2 commas that had no business being there and prevented creating new workspaces

Fix typo preventing the creation of a new workspace

---

automated_provisioning/Dockerfile
automated_provisioning/README.md
automated_provisioning/arm/managed_k8s.json
automated_provisioning/ps/AzureUtilities.ps1
automated_provisioning/ps/ConnectSiloToOrchestrator.ps1
automated_provisioning/ps/CreateK8sCluster.ps1
automated_provisioning/sample_job/RunSampleJob.ps1

Implement the feedback on the _automated_provisioning_ section
```
[x] Bugfix
[x] Feature
```
- Introduce a docker image that contains all the prerequisites
- Various improvements to the instructions in the readme
- Bug fixes (k8s version, adapt to new CLI, login before setting subscription)
Close #26

Improve auto-provisioning resources

---

mlops/internal_silos/ps/ProvisionVanillaSetup.ps1

Increase max cores of orchestrator cluster

beef up orchestrator cluster

---

.github/workflows/python.yaml
examples/pipelines/fl_cross_silo_basic/requirements.txt
requirements.txt

* Add a basic pipeline to an integration test in the build. It will validate an incoming code to avoid any breaking changes whenever there's a new pull request.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
Go to GitHub Actions and look at the pipeline logs.
* Whether the pipeline jobs get initiated when a pull request is created (main, release-sdkv2-mvp branch)
closes #30

add integration validation test - build

---

docs/experiment.md

* Moving documentation to one place.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Documentation to run an FL experiment

---

examples/pipelines/fl_cross_silo_basic/config.yaml
mlops/internal_silos/README.md

- align compute names in the experiment with what's created by the auto-provisioning
- add a reminder in the README that people will need to log in

Small improvements

---

mlops/bicep/modules/orchestrators/orchestrator_open.bicep

Better description for orchestrator bicep script

---

examples/pipelines/fl_cross_silo_factory/config.yaml

Align config of factory experiment with bicep provisioning names

---

README.md

I suggest to make the quickstart more visible on the "homepage" of the repo. And add some color to it.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Add shortcut to quickstart from README

---

docs/README.md

One last read of our docs to suggest a couple changes to the docs/README. The goal was to simplify the wording and also highlight the motivations first and foremost, so that customers that are not familiar with FL will get the value right away. (I hope this PR achieves this goal).
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Propose rewriting of readme to highlight motivation first

---

README.md

Fix link to quickstart from README

---

docs/quickstart.md

Update quickstart to mention rg clean-up

---

docs/quickstart.md

Moving the disclaimer closer to the setup phase to show the different alternatives.

Update quickstart to lower header (hotfix)

---

docs/quickstart.md
examples/pipelines/fl_cross_silo_factory/submit.py
examples/pipelines/fl_cross_silo_literal/submit.py

* Add subscription id, resource group and workspace name as CLI args
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```

Add subscription id, resource group and workspace name as CLI args

---

docs/provisioning/README.md
docs/provisioning/open_orchestrator.md
docs/provisioning/orchestrator_open.md
docs/provisioning/silo_open.md
mlops/arm/open_compute_storage_pair.json
mlops/arm/open_sandbox_setup.json
mlops/bicep/modules/permissions/msi_storage_rw.bicep
mlops/bicep/modules/resources/open_compute_storage_pair.bicep
mlops/bicep/open_sandbox_setup.bicep

This PR creates a home page for an "FL provisioning cookbook" exposing all the self-service options for users to pick and choose their options and create an FL environment.
It also provides one such tutorial for creating an open pair of compute+storage. The bicep code has been upgraded in order to be more usable when used from the cookbook itself. For instance: names of parameter showing up in Azure 1 click deployment UI, setting up permissions within the script to avoid having multiple manual steps, etc.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```

Initiate provisioning "cookbook" with list of provisioning scenarios + example

---

.github/actions/provision-resources/action.yaml
.github/workflows/pipeline-e2e-test.yaml
.github/workflows/release-branch-test.yaml

Make deployment name unique in our github actions

---

docs/provisioning/silo_vnet_newstorage.md

Add a paragraph taken from the official docs on storage private endpoints.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Provide motivation in provisioning docs for using service endpoints

---

docs/provisioning/silo_open.md
docs/provisioning/silo_vnet_newstorage.md
mlops/arm/open_compute_storage_pair.json
mlops/arm/open_sandbox_setup.json
mlops/arm/vnet_compute_storage_pair.json
mlops/arm/vnet_publicip_sandbox_setup.json

This just upgrades all ARM templates based on the latest corresponding bicep files. I also fixed the path to the bicep files in our tutorials.

Refresh provisioning arm buttons with latest from bicep

---

docs/provisioning/silo_vnet_newstorage.md

Fix minor typo orchestrator->silo in provisioning documentation

---

docs/provisioning/README.md
docs/provisioning/silo_open_aks_with_cc.md
mlops/arm/open_aks_with_confcomp_storage_pair.json
mlops/bicep/modules/azureml/attach_aks_training_to_azureml.bicep
mlops/bicep/modules/azureml/deploy_aks_azureml_extension.bicep
mlops/bicep/modules/azureml/deploy_aks_azureml_extension_via_script.bicep
mlops/bicep/modules/computes/open_new_aks_with_confcomp.bicep
mlops/bicep/modules/fl_pairs/open_aks_with_confcomp_storage_pair.bicep

This adds an experimental provisioning tutorial + bicep to create an AKS cluster with confidential compute nodes, Not yet secured with vnet and private endpoints (future work).
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```

Add "open aks with cc" provision tutorial and bicep scripts

---

docs/provisioning/README.md
docs/provisioning/silo_vnet_existingstorage.md
docs/provisioning/silo_vnet_newstorage.md
mlops/arm/vnet_compute_existing_storage.json
mlops/bicep/modules/fl_pairs/vnet_compute_existing_storage.bicep
mlops/bicep/modules/storages/existing_blob_storage_datastore.bicep

* add bicep script to provision aml compute with an existing storage in the SAME tenant
* add tutorial and instructions on how to deploy
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
* wording / usability of the tutorial
Provisioning has been working in tests, we'll reproduce and verify during bug bash.

Provide script + tutorial to attach pair with an existing storage

---

.github/workflows/pipeline-e2e-test.yaml

Building on top of the recent PR #124 , this one just adds all the brand new 2 arm templates from PR #142  and PR #138

Add recent arm templates to diff build

---

docs/provisioning/jumpbox_cc.md

Hotfix: extension typo

---

docs/provisioning/orchestrator_open.md
docs/provisioning/silo_vnet_newstorage.md
examples/pipelines/fl_cross_silo_factory/config.yaml
examples/pipelines/fl_cross_silo_literal/config.yaml

* Add annotations in the config.yaml explaining where users should put their orch/silo settings.
* In https://github.com/Azure-Samples/azure-ml-federated-learning/blob/release-sdkv2-iteration-03/docs/provisioning/orchestrator_open.md path to template was wrong, use fl_pairs instead

Implement feedback from bugbash

---

CHANGELOG.md

This PR should be the last one in this iteration. It just lists the main changes

October release changelog

---

docs/provisioning/external-silos.md

mirroring this hotfix PR to main: https://github.com/Azure-Samples/azure-ml-federated-learning/pull/178
(I know it's not technically required, but I'd rather avoid potential sources of conflict when we'll merge the release branch into main)

different param value for AKS

---

.github/PULL_REQUEST_TEMPLATE.md

* This PR modifies the PR template to prompt the issuer to set expectations for review turnaround time. It just adds the section below to the template.
Urgency:
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: change in PR template
```

include urgency in PR template

---

docs/quickstart.md
docs/real-world-examples/ccfraud.md
docs/real-world-examples/ner.md
docs/real-world-examples/pneumonia.md
examples/pipelines/requirements.txt

Aligning all 3 tutorials with a similar structure and wording. Validate instructions with an outside eye + bug bash.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Standardize all 3 real world example tutorials

---

examples/pipelines/fl_cross_silo_factory/fl_factory.py

Changes to the internal variables in azure-ai-ml made our factory code fail during soft validation. This fixes this my fixing the test.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
* Run the factory test experiment in CI/CD

Fix factory to support latest azure-ai-ml

---

README.md
docs/README.md
docs/tsg.md

Add a guide to help debug most of the typical issues encountered during deployment or experiment.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Implement troubleshooting guide with first typical issues

---

docs/tsg.md

Add data permissions issue to TSG

---

CHANGELOG.md

* Release notes for current iteration
* Please check I didn't mis-represent anything
* Please check I didn't forget anything important

November notes

---

examples/components/CCFRAUD/traininsilo/conda.yaml
examples/components/MNIST/preprocessing/conda.yaml
examples/components/MNIST/traininsilo/conda.yaml
examples/components/NER/preprocessing/conda.yaml
examples/components/NER/traininsilo/conda.yaml
examples/components/NER/upload_data/conda.yaml
examples/components/PNEUMONIA/traininsilo/conda.yaml

Some of the dependencies we were using are stale and might cause vulnerability issues after security scanning. This PR adresses this by reducing the number of dependencies, and upgrading to more recent versions.
Hopefully it doesn't introduce a breaking change.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: dependency updates
```
* run all experiments from scratch, from data upload, again.

Upgrade all pip dependencies to latest

---

.github/workflows/pipeline-e2e-test.yaml
.github/workflows/release-branch-test.yaml
examples/components/utils/aggregatemodelweights/run.py

* Add tests to run industry-relevant pipelines if any changes in the `utils` dir are observed.
Urgency:
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
Do any temp. changes in the utils dir files.
* Check if the industry-relevant workflows are triggered.

Test industry-relevant examples if any changes in the `utils` dir are observed 

---

examples/components/CCFRAUD/preprocessing/run.py
examples/components/CCFRAUD/traininsilo/run.py
examples/components/MNIST/preprocessing/run.py
examples/components/MNIST/traininsilo/run.py
examples/components/NER/preprocessing/run.py
examples/components/NER/traininsilo/run.py
examples/components/PNEUMONIA/traininsilo/run.py

* Title says it all :)
Urgency:
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
closes #168

Make scripts run locally

---

.github/actions/submit-aml-factory-pipeline/action.yaml
.github/actions/submit-aml-literal-pipeline/action.yaml
.github/actions/submit-example-pipeline/action.yaml
.github/actions/submit-upload-data-pipeline/action.yaml
.github/workflows/build-test.yaml
docs/provisioning/external-silos.md
docs/quickstart.md
docs/real-world-examples/ccfraud.md
docs/real-world-examples/ner.md
docs/real-world-examples/pneumonia.md
examples/pipelines/ccfraud/submit.py
examples/pipelines/fl_cross_silo_factory/submit.py
examples/pipelines/fl_cross_silo_literal/submit.py
examples/pipelines/ner/submit.py
examples/pipelines/pneumonia/submit.py
examples/pipelines/utils/upload_data/submit.py

Remove --submit flag and introduce --offline flag when the user do not want to submit the job
Urgency:
```
[X] Yes
[ ] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Change submit to offline with default False

---

examples/components/CCFRAUD/traininsilo/run.py
examples/components/NER/traininsilo/run.py
examples/components/NER/traininsilo/spec.yaml
examples/components/PNEUMONIA/traininsilo/run.py
examples/components/PNEUMONIA/traininsilo/spec.yaml
examples/pipelines/ccfraud/submit.py
examples/pipelines/ner/submit.py
examples/pipelines/pneumonia/submit.py
mlops/arm/open_sandbox_setup.json
mlops/arm/vnet_publicip_sandbox_setup.json

Support DDP for all industrial samples
Urgency:
```
[X] Yes
[ ] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

DDP support for NER + PNEUMONIA

---

examples/pipelines/ccfraud/config.yaml
examples/pipelines/ccfraud/submit.py
examples/pipelines/fl_cross_silo_factory/config.yaml
examples/pipelines/fl_cross_silo_factory/fl_factory.py
examples/pipelines/fl_cross_silo_factory/submit.py
examples/pipelines/fl_cross_silo_literal/config.yaml
examples/pipelines/fl_cross_silo_literal/submit.py
examples/pipelines/ner/config.yaml
examples/pipelines/ner/submit.py
examples/pipelines/pneumonia/config.yaml
examples/pipelines/pneumonia/submit.py

* Introduce silo names in config files in order to give users a bit more flexibility in naming their silos.
Urgency:
```
[x] Yes
[ ] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
Submit any pipeline by providing a custom silo name and then look at the pipeline metrics if the name is reflected correctly.
closes #228

Introduce silo names in config files

---

examples/components/MNIST/preprocessing/run.py

If labels are not provided but transforrms are the dataset loader fails
Urgency:
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix order for get_item in MNIST

---

examples/pipelines/ccfraud/config.yaml
examples/pipelines/ccfraud/submit.py
examples/pipelines/fl_cross_silo_factory/config.yaml
examples/pipelines/fl_cross_silo_factory/fl_factory.py
examples/pipelines/fl_cross_silo_factory/submit.py
examples/pipelines/fl_cross_silo_literal/config.yaml
examples/pipelines/fl_cross_silo_literal/submit.py
examples/pipelines/ner/config.yaml
examples/pipelines/ner/submit.py
examples/pipelines/pneumonia/config.yaml
examples/pipelines/pneumonia/submit.py

* Support multiple computes in all examples.
Urgency:
```
[x] Yes
[ ] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
Submit either a literal or a factory example and check if the preprocessing and training jobs are running on different computes.

Support multiple computes in all examples

---

.github/workflows/release-branch-test.yaml
examples/components/MNIST/preprocessing/run.py

* Update release branch
Urgency:
```
[ ] Yes
[x] No
```

Update release branch

---

docs/provisioning/external-silos.md

* A customer asked to provide the part of the external silo creation instructions for the Silo Admin in a separate document. We are not doing exactly that, for 2 reasons: there is value for the FL Admin to have ALL the steps in a single document, and just copying the Silo Admin instructions into a standalone document means we'd have repeated information and would need to maintain 2 documents. Instead, we are adding to the current document more precisions about what the SIlo Admin needs to do, along with a link to the relevant section. This PR closes #244 
Urgency:
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] …
```

more precisions about FL vs Silo Admin tasks

---

docs/README.md
docs/tutorials/dp-for-cross-silo-fl.md
docs/tutorials/dp-for-cross-silo-horizontal-fl.md

added DP tutorial documentation.
Urgency:
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

added dp toturial

---

docs/concepts/plan-your-fl-project.md

This is just a PR to propose a refactoring of the onboarding guide.

Update for onboarding guide (work in progress)

---

README.md

Add text analytics success story to homepage

---

CHANGELOG.md

Changelog for January 2023 release

---

examples/components/CCFRAUD/traininsilo/conda.yaml
examples/components/CCFRAUD/traininsilo/run.py
examples/components/MNIST/traininsilo/conda.yaml
examples/components/NER/traininsilo/conda.yaml
examples/components/NER/traininsilo/run.py
examples/components/PNEUMONIA/traininsilo/conda.yaml
examples/components/PNEUMONIA/traininsilo/run.py

Update package used for cuda runtime for PyTorch according to installation instructions. Provide fixes for DDP training for some samples
Urgency:
```
[X] Yes
[ ] No
```
```
[X] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix CUDA and DDP training

---

examples/components/CCFRAUD/traininsilo/run.py

Fix issues with CUDA training and PyTorch 1.13.0
Urgency:
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Report AUROC for CCFRAUD

---

docs/concepts/benchmarking.md

A couple of minor edits to the benchmark report before merging.

minor fixes to benchmark report

---

docs/tutorials/vertical-fl.md

Update VFL docs with socket threshold information
Urgency:
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```

Update VFL docs with socket threshold information

---

.github/workflows/release-branch-test.yaml
CHANGELOG.md
examples/pipelines/ccfraud_vertical/submit.py
examples/pipelines/mnist_vertical/submit.py

* Feb. ChangeLog.
* Change `--submit` flag to `--offline` flag in the Vertical FL pipelines to maintain consistency.
Urgency:
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```

ChangeLog + fix minor issues

---

.github/actions/bicep-to-arm-template-diff/action.yaml

* Avoid getting our arm diff check to fail systematically whenever a new version of bicep comes up
* Fix the version intentionally in the build
Urgency:
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```

Use explicit version of bicep

---

docs/README.md
docs/concepts/mlops_for_fl.md

* document how to leverage MLOps in AzureML
* recommend specific settings to restrict execution of prod experiments
Urgency:
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

Add instructions to leverage MLOps to restrict prod FL to peer-reviewed code

---

examples/components/CCFRAUD_VERTICAL/traininsilo/aml_comm.py
examples/components/MNIST_VERTICAL/traininsilo/aml_comm.py

More precise and fine grained metrics for communication
Urgency:
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```

Provide fixes and unified approach for measuring time across communication techniques in VFL

---

examples/pipelines/ccfraud/submit.py

Fix mistake in the component name in the pipeline
Urgency:
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```

Hotfix name of the component

---

CHANGELOG.md

* This PR updates the changelog to include the main changes after our February release.
Urgency:
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
* Make sure that no important change was missed

release notes for March

---

docs/real-world-examples/bank-marketing.md
docs/tutorials/vertical-fl.md

* This PR simplifies the Kaggle credentials part of the Bank Marketing Prediction tutorial. It aligns it with the CCFRAUD tutorial. It also slightly improves the general Vertical FL tutorial (typos, wrong links).
* It closes #324 .
Urgency:
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
* Read the docs, check the links

Simplify Kaggle part in the Bank Marketing Prediction tutorial

---

mlops/arm/sandbox_fl_confidential.json
mlops/arm/sandbox_fl_eyesoff_cpu.json
mlops/arm/sandbox_fl_eyesoff_cpu_gpu.json
mlops/arm/sandbox_fl_eyesoff_gpu.json
mlops/arm/sandbox_fl_eyeson_cpu.json
mlops/arm/sandbox_fl_eyeson_cpu_gpu.json
mlops/arm/sandbox_fl_eyeson_gpu.json
mlops/arm/sandbox_minimal.json
mlops/arm/vnet_publicip_sandbox_aks_confcomp_setup.json
mlops/arm/vnet_publicip_sandbox_setup.json
mlops/bicep/modules/azureml/open_azureml_workspace.bicep

* to avoid policy deny, use allowBlobPublicAccess=false for the workspace storage
* also adds other explicit parameters copied over from orch/silo storages
Urgency:
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```

set allowBlobPublicAccess=false for workspace default storage

---

docs/provisioning/silo_open_aks_with_cc.md

Update docs to resemble structure of the repository.
Urgency:
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```

Docs hotfix

---

docs/tutorials/read-local-data-in-k8s-silo.md
mlops/k8s_templates/README.md

fix broken link

---

examples/cli-jobs/upload-local-data/confidential_io.py
examples/components/CCFRAUD/preprocessing/confidential_io.py
examples/components/CCFRAUD/traininsilo/confidential_io.py
examples/components/CCFRAUD/upload_data/confidential_io.py
examples/components/shared/confidential_io.py

* ...
Urgency:
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```

Do not require RSA key if confidentiality disabled

---

docs/tutorials/e2e-fl-on-cc.md

* This PR adds instructions for a tutorial on FL+CC
Urgency:
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
* Make sure the instructions make sense and are properly written.
* Make sure that the [job](https://ml.azure.com/runs/jolly_oxygen_ml8t6h63lc?wsid=/subscriptions/48bbc269-ce89-4f6f-9a12-c6f91fcb772d/resourcegroups/cc-fl-demo-rg/workspaces/aml-fl-cc-02&tid=72f988bf-86f1-41af-91ab-2d7cd011db47) has succeeded and was using CC properly
* @saketmicrosoft , I need your input especially for that last part

Instructions for FL+CC tutorial

---

CHANGELOG.md

* This PR introduces the (long overdue) change log for April and May.
Urgency:
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
* No big change was overlooked
* The changelog is clearly written

April/May Changelog

---

CHANGELOG.md
README.md
docs/README.md
docs/concepts/vertical-fl.md

*  Fix broken links to bank marketing tutorial
Urgency:
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```

fix broken links to bank marketing tutorial
